modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="bdlmod"
version="${file.jarVersion}"
displayName="Blue's Dynamic Lights Mod"
#updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/blues-dynamic-lights"
logoFile="logo.png"
#credits=""
authors="Blue Paint"
description='''
Light up your world.'''

[[dependencies.bdlmod]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.0,)"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.bdlmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
