modLoader="javafml"
loaderVersion="[43,)"
license="MIT"

[[mods]]
modId="bdlmod"
version="${file.jarVersion}"
displayName="Blue's Dynamic Lights Mod"
#updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/create" #MAKE SURE TO CHANGE
logoFile="logo.png"
#credits=""
authors="Blue Paint"
description='''
Light up your world.'''

[[dependencies.bdlmod]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.1,)"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.bdlmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"